Add Full Assigned Jurisdiction Path to Patient profile
SaraAlert/saraalert-fhir-ig pull request #4
Opened 2020-11-02 21:18 UTC by tstrass

2020-11-02 22:41 UTC, jawalonoski reviewed
This looks fine and straight-forward.

What is the purpose of the new jurisdiction extension? Is it just informative? If so, String is fine.

But if it is more than that -- e.g. applications might edit the value and attempt to switch patients jurisdictions -- then maybe the string value is not such a great idea. The question then becomes, how does the web app do that today? By altering the string, or an identifier, or something else? Food for your thought.

2020-11-04 12:56 UTC, ngfreiter requested changes
This looks good, just a typo that is causing some errors during building that needs to be fixed.

2020-11-04 12:56 UTC, ngfreiter commented on fsh/patient.fsh
> +  full-assigned-jurisdiction-path named full-assigned-jurisdiction-path 0..1 MS and
The extra `and` at the end of the line here is making SUSHI not so happy.

2020-11-04 12:56 UTC, ngfreiter commented on fsh/patient.fsh
> +Description: "Represents the jurisdiction in which this Patient is enrolled."
You could consider having this description use "monitoree" instead of "Patient", for sake of consistency with other descriptions.

2020-11-04 21:23 UTC, tstrass commented
> What is the purpose of the new jurisdiction extension? Is it just informative? If so, String is fine.
> 
> But if it is more than that -- e.g. applications might edit the value and attempt to switch patients jurisdictions -- then maybe the string value is not such a great idea. The question then becomes, how does the web app do that today? By altering the string, or an identifier, or something else? Food for your thought.

It's not just informative- it's there so that client apps can assign monitoree jurisdiction. As far as I can tell, this is the same way it works in the UI, although that certainly doesn't mean we need to do it that way in the API. I'd prefer something more structured than a comma separated string, though I'll have to figure out what all can go in that string (since I know it's not as simple as just <country>, <state>, <county>). @jawalonoski

2020-11-06 21:44 UTC, ngfreiter approved these changes

2020-11-10 14:40 UTC, merged