SARAALERT-1032: API Support for Foreign Address
SaraAlert/saraalert-fhir-ig pull request #7
Opened 2021-01-29 15:32 UTC by ngfreiter

This PR adds an `address-type` extension that can be used on the `Patient.address` array. This is done so that the API can support foreign addresses.

The PR implementing this is here: https://github.com/SaraAlert/SaraAlert/pull/686.

2021-02-04 20:01 UTC, tstrass requested changes
I like how this is defined. Just one small wording suggestion

2021-02-04 20:01 UTC, tstrass commented on input/fsh/patient.fsh
> +* address ^slicing.description = "Slice to distinguish a Foreign Address."
```suggestion
* address ^slicing.description = "Slice to distinguish a Foreign Address (outside of the USA)."
```

2021-02-08 20:13 UTC, ngfreiter commented on input/fsh/patient.fsh
> +* address ^slicing.description = "Slice to distinguish a Foreign Address."
Addressed in https://github.com/SaraAlert/saraalert-fhir-ig/pull/7/commits/439da6b2d218c61f2a631eca7a28475aef0f05b8

2021-02-09 14:41 UTC, tstrass approved these changes

2021-02-09 14:42 UTC, merged